server:
  port: 8083
spring:
  application:
    name: order-service
    port: 8083
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8082
          jwk-set-uri: http://auth-service:8082/oauth2/jwks
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/order_service
    username: admin
    password: admin
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog-master.yaml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

springdoc:
  swagger-ui:
    csrf:
      enabled: true
swagger-server: http://localhost:8083/
feign:
  user:
    service:
      mock: /api/v1/users/user/by-email.*
      url: http://user-service:8080/api/v1/users/
      info-endpoint: user/by-email
      name: user-service
      port: 8080