server:
  port: 80
spring:
  application:
    name: order-service
    port: 80
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service
          jwk-set-uri: http://auth-service/oauth2/jwks
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/order_service
    username: admin
    password: admin
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog-master.yaml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  kafka:
    bootstrap-servers: http://kafka:9092
    trusted-packages: com.innowise.external.dto.kafka

springdoc:
  swagger-ui:
    csrf:
      enabled: true
swagger-server: http://order-service:8083/
feign:
  user:
    service:
      mock: /api/v1/users/user/by-email.*
      url: http://user-service/api/v1/users/
      info-endpoint: user/by-email
      name: user-service
      port: 80

kafka:
  topic:
    payment-result-topic: payment.result.msg
    order-created-topic: order.created.msg