server:
  port: ${PORT}
spring:
  application:
    name: order-service
    port: ${PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER}
          jwk-set-uri: ${AUTH_JWKS}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/order_service
    username: admin
    password: admin
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog-master.yaml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  kafka:
    bootstrap-servers: http://${KAFKA_HOST}:9092
    trusted-packages: com.innowise.external.dto.kafka
  profiles:
    default: ${SPRING_PROFILE}

springdoc:
  swagger-ui:
    csrf:
      enabled: true
swagger-server: http://order-service:8083/
feign:
  user:
    service:
      mock: /api/v1/users/user/by-email.*
      url: http://${USER_SERVICE_ADDR}/api/v1/users/
      info-endpoint: user/by-email
      name: user-service
      port: ${USER_SERVICE_MOCK_PORT}

kafka:
  topic:
    payment-result-topic: payment.result.msg
    order-created-topic: order.created.msg

otel:
  traces:
    sampler: always_on
  exporter:
    otlp:
      traces:
        endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
        protocol: grpc
      metrics:
        endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
        protocol: grpc
      logs:
        endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
        protocol: grpc